parameters:
  - name: displayName
    type: string
jobs:
- job: ${{ parameters.displayName }}
  
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: 'ubuntu-latest'    
  steps:
  - template: ../steps/sonarcube-quality-check.yaml
