parameters:
  - name: displayName
    type: string

  - name: command
    type: string


jobs:
- job: ${{ parameters.displayName }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: 'ubuntu-latest'
  
  steps:
  - template: ../steps/run-sonarcloudanalysis.yaml
    parameters:
      command: './gradlew clean sonarqube --stacktrace -Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError" -Psonar.login=8a5104e3e0960afa90a93fac3c56aae2fa4794d8' 
  
