---
trigger:
  - none

parameters:
  - name: environments
    type: object
    default: 
    - name: test
      subscription: DTS-SHAREDSERVICES-TEST
      group: HMI-APIM-BUILD-TEST
      condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
      tests_gradle1:
      - name: Sonarqube Test
        command: test
        
jobs:
- template: pipeline/jobs/sonarqubetest.yaml
  parameters:
    displayName: ${{ test.name }}
    command: ${{ test.command }}
        

    

    

        
