---
trigger:
  - none

parameters:
- name: test
  command: test
         
jobs:
- template: pipeline/jobs/sonarqubetest.yaml
  parameters:
    displayName: ${{ test.name}}
    command: ${{ test.command }}
        

    

    

        
