---
trigger:
  - none

parameters:
- name: command
  type: string
- name: displayname
  type: string
       
jobs:
- template: pipeline/jobs/sonarqubetest.yaml
  parameters:
    displayName: ${{ parameters.displayname}}
    command: ${{ parameters.command }}
        

    

    

        
