---
trigger:
  - none

parameters:
- name: test
  subscription: DTS-SHAREDSERVICES-TEST
  group: HMI-APIM-BUILD-TEST
  tests_sonarqube:
  - name: UnitTest
    command: test
         
jobs:
- template: pipeline/jobs/sonarqubetest.yaml
  parameters:
    displayName: ${{ test.name}}
    command: ${{ test.command }}
        

    

    

        
