---
trigger:
  - none

parameters:
- name: displayname
  type: string
       
jobs:
- template: pipeline/jobs/sonarqubetest.yaml
  parameters:
    displayName: ${{ parameters.displayname}}
    
        

    

    

        
